### ISSUE TITLE
Golines is slow on some files

### ISSUE THREAD

**Issue by ayoisaiah** [segmentio/golines#33] opened 2021-05-21 07:46 UTC
On my machine, golines is an order of magnitude slower than `gofmt`. What could be causing this issue?

![image](https://user-images.githubusercontent.com/13372163/119101175-9cedb800-ba10-11eb-863c-9f37932d7ac8.png)

I'm on the latest version: v04.0

**Comment by yolken-segment** [comment] 2021-05-21 16:43
Do you see this difference on all files or just the specific `src/operation.go` one you're showing in your screenshot? If the latter, is there anything specific about that file (e.g., length, style of code, etc.) that you can share?

Golines will be slower than the alternatives since it's doing more processing, but I've never seen it take multiple seconds to format a single file, so will be interesting to dig in here and figure out what's going on.

**Comment by ayoisaiah** [comment] 2021-05-21 16:49
It's much better on shorter files. Here's a link to the `src/operation.go` file: https://github.com/ayoisaiah/f2/blob/master/src/operation.go

![image](https://user-images.githubusercontent.com/13372163/119171604-b3b9fc00-ba5c-11eb-96bf-e9e51ce8c9cf.png)

**Comment by yolken-segment** [comment] 2021-05-21 17:05
Cool, thanks for sharing the link to the file. Will do some debugging on my side.

**Comment by yolken-segment** [comment] 2021-07-12 00:56
Ok, finally took a look at this, and I'm having trouble reproducing. Golines is a bit slower than goimports on your [sample file](https://github.com/ayoisaiah/f2/blob/master/src/operation.go), but the time taken doesn't look too terrible on my system:

```
Benjamins-MacBook-Pro:golines benjamin.yolken$ time golines -m 80 -w ./_fixtures/operation.go

real	0m0.168s
user	0m0.177s
sys	0m0.424s
```

vs.

```
Benjamins-MacBook-Pro:golines benjamin.yolken$ time goimports ./_fixtures/operation.go > /tmp/out.go

real	0m0.075s
user	0m0.074s
sys	0m0.224s
```

Can you provide more information about your system?

**Comment by ayoisaiah** [comment] 2021-07-12 21:28
I don't know why I'm getting such crazy times
![image](https://user-images.githubusercontent.com/13372163/125358083-61ac9d00-e360-11eb-98ce-c0d983929300.png)

What would you like to know?

**Comment by yolken-segment** [comment] 2021-07-12 21:54
Out of curiosity- what operating system type and version are you running?

Another thing that could be helpful- can you run one of the slow `golines` commands with the `--profile=out.pprof` flag and either attach that profile file or post a screenshot of the graph you get from running `go tool pprof -http=localhost:9090 out.prof`?

**Comment by ayoisaiah** [comment] 2021-07-12 22:02
This is on Ubuntu 20.04 on Windows 10 (WSL2). Interestingly, the profile is showing much lower times compared to what I'm getting.

[out.zip](https://github.com/segmentio/golines/files/6804619/out.zip)

**Comment by yolken-segment** [comment] 2021-07-13 19:32
Yeah, took a look at the profile and it looks pretty similar to the one on my machine. My guess is that there's something else going on in your environment (e.g., some sort of security scanning process?) outside of golines itself that's slowing it down.

I don't have any experience with WSL, but will try to set it up and play with golines on it to see if I can reproduce any slowdowns.

**Comment by ayoisaiah** [comment] 2021-07-17 18:51
The output in powershell is more like it:

```
$  Measure-Command { golines -m 80 -w .\src\operation.go }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 93
Ticks             : 931454
TotalDays         : 1.07807175925926E-06
TotalHours        : 2.58737222222222E-05
TotalMinutes      : 0.00155242333333333
TotalSeconds      : 0.0931454
TotalMilliseconds : 93.1454
```

**Comment by yolken-segment** [comment] 2021-07-19 17:54
I tried golines on Ubuntu 20.04 in WSL2 and I didn't notice any performance issues:

![golines](https://user-images.githubusercontent.com/54862872/126204370-054159a2-c001-400f-83aa-4bbab83fd1cb.png)

So, I think there's something specific to your setup going on that's independent of golines itself.

**Comment by ayoisaiah** [comment] 2021-07-19 20:46
Thanks for taking the time to look at this. It appears that you are right, I tried it on a different system with similar results.

I have no idea what could be causing the issue, and I'm not experiencing such slowdowns with other tools. 

Since this appears to be specific to my system, we can close this issue.

**Comment by yolken-segment** [comment] 2021-07-19 20:50
@ayoisaiah ok, sorry about that! Hope you're able to figure out what's going on here.

**Closed by yolken-segment** 2021-07-19 20:50 UTC
Labels: bug

**Comment by ayoisaiah** [comment] 2021-07-19 20:57
No worries, I'll probably stick to using in my pre-commit hooks for now

**Comment by errx** [comment] 2021-09-30 12:37
Found the problem.

If `goimports` is available in $PATH then golines will try to use it as the underlying formatter otherwise it will use gofmt. And it turns out that `goimports` is way slower than gofmt

**Comment by ayoisaiah** [comment] 2021-09-30 13:08
@errx Wow, that appears to be totally correct!

![image](https://user-images.githubusercontent.com/13372163/135460784-ad5e457a-f827-46c7-9358-85f16d979ff2.png)

See the difference above. I renamed the `goimports` binary in a different terminal before running the command again

@yolken-segment thoughts on this?

**Comment by yolken-segment** [comment] 2021-09-30 16:18
Hmm, interesting. `goimports` is reasonably fast on my machine. I wonder if there's something up with how it runs on WSL2?

In any case, note that you can change the base formatter used with the `--base-formatter` flag, e.g. `golines --base-formatter=gofmt [other arguments]` will force it to use `gofmt` even if `goimports` is in the PATH.

**Comment by ayoisaiah** [comment] 2021-09-30 16:36
Something must be up. `goimports` is also quite fast on my machine:

```
$ time goimports -w src/operation.go
________________________________________________________
Executed in   16.13 millis    fish           external
   usr time   27.82 millis  398.00 micros   27.42 millis
   sys time    0.31 millis  314.00 micros    0.00 millis
```

![image](https://user-images.githubusercontent.com/13372163/135495605-4a8c5273-923a-4c29-8cef-1e20201052db.png)

**Comment by Laurence-Caraccio** [comment] 2022-09-15 15:10
Just to add to this as I encountered it recently, it seems to be when passing content of a file to `goimports` via stdin that's in a subfolder:

```
# stdin in subfolder
(cloudeng) ~/Desktop/repos/lambda-go-mds-integration  (main) (k8s: dev) $ time cat mds/insurance_csv_files.go | goimports >> /dev/null

real	0m5.232s
user	0m7.632s
sys	0m29.804s

# file as param in subfolder
(cloudeng) ~/Desktop/repos/lambda-go-mds-integration  (main) (k8s: dev) $ time goimports mds/insurance_csv_files.go >> /dev/null

real	0m0.019s
user	0m0.006s
sys	0m0.006s

# stdin in current folder
(cloudeng) ~/Desktop/repos/lambda-go-mds-integration  (main) (k8s: dev) $ cd mds/
(cloudeng) ~/Desktop/repos/lambda-go-mds-integration/mds  (main) (k8s: dev) $ time cat insurance_csv_files.go | goimports >> /dev/null

real	0m0.013s
user	0m0.007s
sys	0m0.007s
(cloudeng) ~/Desktop/repos/lambda-go-mds-integration/mds  (main) (k8s: dev) $ 
```

Using the `-v` option on `goimports` I can see it doing a bunch of extra stuff.

```
2022/09/15 16:06:27.335077 24.022778ms for GOROOT= GOPATH= GO111MODULE= GOPROXY= PWD=/Users/laurence/Desktop/repos/lambda-go-mds-integration go env -json GO111MODULE GOFLAGS GOINSECURE GOMOD GOMODCACHE GONOPROXY GONOSUMDB GOPATH GOPROXY GOROOT GOSUMDB GOWORK
2022/09/15 16:06:27.335225 loading package names for 7 packages
...
2022/09/15 16:06:27.638354 gopathwalk: scanned /Users/laurence/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1 in 334.442µs
2022/09/15 16:06:27.638406 gopathwalk: scanning /Users/laurence/go/pkg/mod
2022/09/15 16:06:27.638449 Directory added to ignore list: /Users/laurence/go/pkg/mod/cache
2022/09/15 16:06:32.568616 gopathwalk: scanned /Users/laurence/go/pkg/mod in 4.930061658s
2022/09/15 16:06:32.568714 cfg candidate 1/40: golang.org/x/tools/go/cfg in /Users/laurence/go/pkg/mod/golang.org/x/tools@v0.1.13-0.20220812184215-3f9b119300de/go/cfg
2022/09/15 16:06:32.568733 cfg candidate 2/40: golang.org/x/tools/go/cfg in /Users/laurence/go/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/go/cfg
...
2022/09/15 16:06:32.591596 loaded exports in dir /Users/laurence/go/pkg/mod/golang.org/x/tools@v0.1.9/go/cfg (package cfg): Block, CFG, New
2022/09/15 16:06:32.591689 loaded exports in dir /Users/laurence/go/pkg/mod/golang.org/x/tools@v0.1.0/go/cfg (package cfg): Block, CFG, New
```

Not 100% sure why it behaves this way but thought it might be of interest.
